name: bool_objects
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_database: ^9.1.4
  firebase_core: ^1.22.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  built_collection: ^5.1.1
  rxdart: ^0.27.5
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1

dev_dependencies:
  test: 1.21.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

