// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-iu-LlILZhIUVCejXnryfFh16KRmTEM',
    appId: '1:692486070838:android:2307dd4478f2ce9d0a6e97',
    messagingSenderId: '692486070838',
    projectId: 'test-project-7532e',
    databaseURL: 'https://test-project-7532e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-project-7532e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXieQGuUEs_lMB7d-DUSTLPzP81aBtrbI',
    appId: '1:692486070838:ios:51bbf599a7cde25c0a6e97',
    messagingSenderId: '692486070838',
    projectId: 'test-project-7532e',
    databaseURL: 'https://test-project-7532e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-project-7532e.appspot.com',
    iosClientId: '692486070838-jkla0m8g45nlsksep38en0hiehnv7mgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.boolObjects',
  );
}
